[project]
name = "heart_problem_detector"
version = "0.1.0"
dependencies = [
    "streamlit==1.44.0",
    "pandas==2.1.4",
    "numpy==1.26.4",
    "scikit-learn==1.2.2",
    "joblib==1.2.0"
]
requires-python = "==3.11.*"
